---
stages:
<<<<<<< Updated upstream:.pipeline/ config.yml
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "org-AOS-dev"
    cfSpace: "QuoteSMART Development"
    cfAppName: "tmstest"
    cfCredentialsId: "deploy-dev-cf"
    tmsUpload: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "iDeal_Quality"
    credentialsId: "tms-key"
=======
  build:
    buildTool: "mta"
    buildDescriptor: "mta.yaml"
    buildToolVersion: "MBTJ21N24"
  malwareScan:
    scan: false
  release:
    cfDeploy:
      strategy: "default"
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "org-AOS-dev"
      space: "QuoteSMART Development"
      credential: "deploy-dev-cf"
    cloudTransportManagement:
      nodeOperation: "upload"
      nodeName: "iDeal_Development"
      credential: "tms-key"
>>>>>>> Stashed changes:.sap_cid/ config.yaml
